name: Deploy All

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r ./backend_rds ./backend_redis docker-compose.yml ubuntu@13.60.167.182:~/project
      - name: SSH into EC2 and restart Docker containers
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.60.167.182 << 'EOF'
          cd ~/project
          docker-compose down
          docker-compose up -d
          EOF

  deploy-frontend:
    needs: deploy-backend 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Sync frontend with S3
        run: |
          aws s3 sync ./frontend/templates s3://mini.backend.s3bucket.demo --delete
