name: Deploy Backend and Frontend

on:
  push:
    branches:
      - main

jobs:
  build-rds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build RDS Image
        run: |
          docker build -t backend_rds ./backend_rds
      - name: Push RDS Image to Registry
        run: |
          # Replace with your Docker registry details
          docker tag backend_rds your-registry/backend_rds:latest
          docker push your-registry/backend_rds:latest

  build-redis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Redis Image
        run: |
          docker build -t backend_redis ./backend_redis
      - name: Push Redis Image to Registry
        run: |
          # Replace with your Docker registry details
          docker tag backend_redis your-registry/backend_redis:latest
          docker push your-registry/backend_redis:latest

  deploy-backend:
    needs: [build-rds, build-redis]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up AWS EC2 Instance Connect
        uses: aws-actions/aws-ec2-instance-connect@v1
        with:
          instance-id: ${{ secrets.EC2_INSTANCE_ID }}
          region: eu-north-1
      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r ./backend_rds ./backend_redis docker-compose.yml ubuntu@16.171.28.229:~/project
      - name: SSH into EC2 and restart Docker containers
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@16.171.28.229 << 'EOF'
          cd /home/ubuntu
          docker-compose down
          docker-compose up -d
          EOF

  sync-frontend:
    needs: deploy-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Sync frontend with S3
        run: |
          aws s3 sync ./frontend s3://frontend-static-bucket --delete